"""RepoMori machine-readable repository packer."""

from .codec import (
    SCHEMA_VERSION,
    benchmark_repo,
    build_capsule,
    build_context_bundle,
    build_handoff_package,
    build_pack,
    build_repo_brief,
    check_handoff_package,
    compare_packs,
    diagnose_query,
    evaluate_pack,
    format_benchmark_markdown,
    format_brief_markdown,
    format_compare_markdown,
    format_context_markdown,
    format_eval_markdown,
    format_snapshot_markdown,
    get_file_bytes,
    info_pack,
    query_pack,
    snapshot_repo,
    verify_pack,
)

__all__ = [
    "SCHEMA_VERSION",
    "benchmark_repo",
    "build_capsule",
    "build_context_bundle",
    "build_handoff_package",
    "build_pack",
    "build_repo_brief",
    "check_handoff_package",
    "compare_packs",
    "diagnose_query",
    "evaluate_pack",
    "format_benchmark_markdown",
    "format_brief_markdown",
    "format_compare_markdown",
    "format_context_markdown",
    "format_eval_markdown",
    "format_snapshot_markdown",
    "get_file_bytes",
    "info_pack",
    "query_pack",
    "snapshot_repo",
    "verify_pack",
]
